import { CONTACT_CONFIG } from '../lib/config'

export default function Footer() {
  const year = new Date().getFullYear()
    return (
        <footer className="bg-gray-900 text-gray-300 py-10 px-4">
              <div className="max-w-5xl mx-auto">
                      <div className="flex flex-col md:flex-row gap-6 justify-between mb-8">
                                <div>
                                            <div className="flex items-center gap-3 mb-2">
                                                          <img
                                                                          src="/ucsg-logo.jpg"
                                                                                          alt="UCSG Logo"
                                                                                                          className="h-8 w-auto brightness-0 invert"
                                                                                                                          onError={(e) => { (e.currentTarget as HTMLImageElement).style.display = 'none' }}
                                                                                                                                        />
                                                                                                                                                      <span className="font-bold text-white">Universal Consulting Service Group</span>
                                                                                                                                                                  </div>
                                                                                                                                                                              <p className="text-sm text-gray-400 max-w-xs">
                                                                                                                                                                                            Immigration consulting services for international students.
                                                                                                                                                                                                          Not a law firm. Not legal advice.
                                                                                                                                                                                                                      </p>
                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                          <div className="space-y-1 text-sm">
                                                                                                                                                                                                                                                      <p className="font-semibold text-white mb-2">Contact</p>
                                                                                                                                                                                                                                                                  <p><a href={CONTACT_CONFIG.phone.href} className="hover:text-white">{CONTACT_CONFIG.phone.display}</a></p>
                                                                                                                                                                                                                                                                              <p><a href={`mailto:${CONTACT_CONFIG.email}`} className="hover:text-white">{CONTACT_CONFIG.email}</a></p>
                                                                                                                                                                                                                                                                                          <p className="text-gray-500">Mon–Fri 10 AM – 5 PM ET</p>
                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                              <div className="space-y-1 text-sm">
                                                                                                                                                                                                                                                                                                                          <p className="font-semibold text-white mb-2">Legal</p>
                                                                                                                                                                                                                                                                                                                                      <p><a href="/privacy-policy" className="hover:text-white">Privacy Policy</a></p>
                                                                                                                                                                                                                                                                                                                                                  <p><a href="/terms-of-service" className="hover:text-white">Terms of Service</a></p>
                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                            <div className="border-t border-gray-700 pt-6 text-xs text-gray-500 text-center space-y-1">
                                                                                                                                                                                                                                                                                                                                                                                      <p>© {year} Universal Consulting Service Group. All rights reserved.</p>
                                                                                                                                                                                                                                                                                                                                                                                                <p>
                                                                                                                                                                                                                                                                                                                                                                                                            UCSG is an immigration consulting firm, not a law firm. Information on this site is
                                                                                                                                                                                                                                                                                                                                                                                                                        educational only and does not constitute legal advice.
                                                                                                                                                                                                                                                                                                                                                                                                                                  </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                            <p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                        Results may vary. No outcome is guaranteed. Consult a licensed immigration attorney
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    for advice specific to your situation.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </footer>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }