import { useEffect } from 'react'
import { Link } from 'react-router-dom'
import { CONTACT_CONFIG } from '../lib/config'

export default function ThankYouPage() {
  const calendarUrl = CONTACT_CONFIG.calendar.url

    useEffect(() => {
        window.scrollTo(0, 0)
          }, [])

            return (
                <div className="min-h-screen bg-blue-50 flex flex-col items-center justify-center px-4 py-16">
                      <div className="max-w-2xl w-full bg-white rounded-2xl shadow-lg p-8 text-center">
                              <div className="text-6xl mb-4">✅</div>
                                      <h1 className="text-2xl md:text-3xl font-extrabold text-gray-900 mb-3">
                                                Thank You — We Received Your Evaluation!
                                                        </h1>
                                                                <p className="text-gray-600 mb-6">
                                                                          A UCSG advisor will review your profile and reach out within one business day.
                                                                                    Office hours: Mon–Fri 10 AM – 5 PM ET.
                                                                                            </p>

                                                                                                    {calendarUrl ? (
                                                                                                              <div className="mb-8">
                                                                                                                          <p className="font-semibold text-gray-900 mb-3">
                                                                                                                                        Want to schedule your consultation now?
                                                                                                                                                    </p>
                                                                                                                                                                <a
                                                                                                                                                                              href={calendarUrl}
                                                                                                                                                                                            target="_blank"
                                                                                                                                                                                                          rel="noopener noreferrer"
                                                                                                                                                                                                                        className="inline-block bg-blue-700 text-white font-bold px-8 py-3 rounded-xl hover:bg-blue-800 transition-colors"
                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                  Book My Free Consultation
                                                                                                                                                                                                                                                              </a>
                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                ) : (
                                                                                                                                                                                                                                                                                          <div className="mb-8 bg-blue-50 rounded-xl p-4">
                                                                                                                                                                                                                                                                                                      <p className="text-gray-700 font-medium mb-2">Prefer to call directly?</p>
                                                                                                                                                                                                                                                                                                                  <a
                                                                                                                                                                                                                                                                                                                                href={CONTACT_CONFIG.phone.href}
                                                                                                                                                                                                                                                                                                                                              className="inline-block bg-blue-700 text-white font-bold px-8 py-3 rounded-xl hover:bg-blue-800 transition-colors"
                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                        Call {CONTACT_CONFIG.phone.display}
                                                                                                                                                                                                                                                                                                                                                                                    </a>
                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                      )}

                                                                                                                                                                                                                                                                                                                                                                                                              <p className="text-sm text-gray-500 mb-4">
                                                                                                                                                                                                                                                                                                                                                                                                                        Or email us at{' '}
                                                                                                                                                                                                                                                                                                                                                                                                                                  <a href={`mailto:${CONTACT_CONFIG.email}`} className="text-blue-700 underline">
                                                                                                                                                                                                                                                                                                                                                                                                                                              {CONTACT_CONFIG.email}
                                                                                                                                                                                                                                                                                                                                                                                                                                                        </a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <Link to="/" className="text-blue-700 underline text-sm hover:text-blue-900">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ← Back to Home
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }